version: 2

jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          command: .circleci/run_docker_build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
