version: 2

jobs:
  build:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout
      - run:
          command: |
            # Install Homebrew
            ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
            # Install Cask
            brew install caskroom/cask/brew-cask
            # Install docker toolbox
            brew cask install docker-toolbox
            .circleci/run_docker_build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
